//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Model
    {
        public int Model_ID { get; set; }
        public string Model_Name { get; set; }
        public string Model_Body_Type { get; set; }
        public string Model_Engine_Type { get; set; }
        public Nullable<int> Model_Price { get; set; }
        public Nullable<int> Model_In_Stock { get; set; }
        public Nullable<int> Make_ID { get; set; }
        public string Model_Description { get; set; }
    
        public virtual Car_Make Car_Make { get; set; }
    }
}
