//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Volkswagen_NCAEntities : DbContext
    {
        public Volkswagen_NCAEntities()
            : base("name=Volkswagen_NCAEntities")
        {
      base.Configuration.ProxyCreationEnabled = false;
      base.Configuration.LazyLoadingEnabled = false;
    }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car_Make> Car_Make { get; set; }
        public virtual DbSet<Car_Model> Car_Model { get; set; }
    }
}
